# Generated by Django 6.0.2 on 2026-02-26 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_job_salary_skill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Requirement',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='skill_name',
            new_name='requirement',
        ),
    ]
