# Generated by Django 6.0.2 on 2026-02-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_skill_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirement',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
