# Generated by Django 6.0.2 on 2026-02-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_requirement_delete_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='requirement',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
